In [1]:
import pandas as pd
pd.__version__


'2.2.2'

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [3]:
df.to_csv('laptops.csv')


In [4]:
df1 = pd.read_csv('laptops.csv')
df1.shape[0]

2160

In [5]:
df1['Brand']

0         Asus
1       Alurin
2         Asus
3          MSI
4           HP
         ...  
2155     Razer
2156     Razer
2157     Razer
2158     Razer
2159     Razer
Name: Brand, Length: 2160, dtype: object

In [6]:
print(len(pd.unique(df1['Brand'])))

27


In [7]:
df1.isnull().sum()

Unnamed: 0         0
Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [8]:
df1.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])

## Maxumum price of Dell note books in the dataset

In [9]:
max_price = df1.loc[df1['Brand'] == 'Dell', 'Final Price'].max()
round(max_price)

3936

In [10]:
series = pd.Series(df1['Brand'])
dell_series = series[series=='Dell']
dell_series


161     Dell
271     Dell
281     Dell
319     Dell
328     Dell
        ... 
1843    Dell
1844    Dell
1845    Dell
1846    Dell
1847    Dell
Name: Brand, Length: 84, dtype: object

## Median of Screen columns

In [11]:
median = df1['Screen'].median()
median

15.6

## Most frequent value of Screen column

In [12]:
most_freq_value = df1['Screen'].value_counts().idxmax()
most_freq_value

15.6

## Count of columns with missing values

In [13]:
count = len(df1.columns[df1.isnull().any()].tolist())
count

3

## Fill the missing values with most frequent value

In [14]:
df1['Screen'] = df1['Screen'].fillna(most_freq_value)
df1

Unnamed: 0                                             Laptop  \
0              0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...   
1              1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...   
2              2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...   
3              3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...   
4              4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...   
...          ...                                                ...   
2155        2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...   
2156        2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...   
2157        2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...   
2158        2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...   
2159        2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...   

           Status   Brand       Model                CPU  RAM  Storage  \
0             New    Asus  ExpertBook      Intel Core i5    8      512   
1             New  Alurin          Go      Intel Celeron    8      256   
2             New    Asus  ExpertBook      Intel Core i3    8      256   
3             New     MSI      Katana      Intel Core i7   16     1000   
4             New      HP         15S      Intel Core i5   16      512   
...           ...     ...         ...                ...  ...      ...   
2155  Refurbished   Razer       Blade      Intel Core i7   16     1000   
2156  Refurbished   Razer       Blade      Intel Core i7   16     1000   
2157  Refurbished   Razer       Blade      Intel Core i7   32     1000   
2158  Refurbished   Razer        Book  Intel Evo Core i7   16     1000   
2159  Refurbished   Razer        Book  Intel Evo Core i7   16      256   

     Storage type       GPU  Screen Touch  Final Price  
0             SSD       NaN    15.6    No      1009.00  
1             SSD       NaN    15.6    No       299.00  
2             SSD       NaN    15.6    No       789.00  
3             SSD  RTX 3050    15.6    No      1199.00  
4             SSD       NaN    15.6    No       669.01  
...           ...       ...     ...   ...          ...  
2155          SSD  RTX 3060    17.3    No      2699.99  
2156          SSD  RTX 3070    17.3    No      2899.99  
2157          SSD  RTX 3080    17.3    No      3399.99  
2158          SSD       NaN    13.4   Yes      1899.99  
2159          SSD       NaN    13.4   Yes      1699.99  

[2160 rows x 13 columns]

In [15]:
new_median = df1.Screen.median()
new_median

15.6

## Sum of Weights

In [16]:
innjoo_laptops = df1.loc[df1['Brand'] == 'Innjoo', ['RAM','Storage','Screen']]
innjoo_laptops


RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [17]:
## Get the array and name it X
X = innjoo_laptops.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [24]:
import numpy as np
XTX = np.matmul(X, X.T) + 1e-6 * np.eye(XTX.shape[0])
XTX

array([[ 65843.360001, 131379.36    ,  16635.96    ,  16651.96    ,
         33035.96    ,  33035.96    ],
       [131379.36    , 262451.360001,  33019.96    ,  33035.96    ,
         65803.96    ,  65803.96    ],
       [ 16635.96    ,  33019.96    ,   4310.810001,   4318.81    ,
          8414.81    ,   8414.81    ],
       [ 16651.96    ,  33035.96    ,   4318.81    ,   4330.810001,
          8426.81    ,   8426.81    ],
       [ 33035.96    ,  65803.96    ,   8414.81    ,   8426.81    ,
         16618.810001,  16618.81    ],
       [ 33035.96    ,  65803.96    ,   8414.81    ,   8426.81    ,
         16618.81    ,  16618.810001]])

In [26]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 546595.67760194, -171405.43661978,  255448.52455541,
        -270517.51234314, -200017.55741974, -200017.55741974],
       [-171405.21785904,   73243.78003792,  -66833.25082629,
         184370.91141879,   -4466.75735339,   -4466.75735339],
       [ 255448.67349919,  -66833.39976981,  128419.14947509,
         -58653.08610605, -139223.38979691, -139223.38979691],
       [-270516.39526729,  184370.66938566,  -58652.49033245,
         642172.5897015 , -244104.96835324, -244104.96835324],
       [-200018.31144613,   -4466.44084849, -139223.68768356,
        -244104.18640024,  804782.99239326, -195216.6690711 ],
       [-200018.31144613,   -4466.44084849, -139223.68768356,
        -244104.18640024, -195216.6690711 ,  804782.99239326]])

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y
y.shape[0]

6

In [34]:
#w = np.matmul(np.matmul(inv_XTX, X.T), y)
temp = np.matmul(inv_XTX, X.T)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 6)